server:
  port: 8080
management:
  security:
    enabled: false
DB4:
  url: jdbc:oracle:thin:@dc1prd-scan:1521/inqprd.ipacc.com
  username: inquiry_user
  password: intranet932
TGDBSERVER1DataSource:
  url: jdbc:oracle:thin:@dc1prd-scan:1521/prd1
  username: polnote_service
  password: pr0dn0tes
TGDBSERVER2DataSource:
  url: jdbc:oracle:thin:@dc1prd-scan:1521/prd2
  username: polnote_service
  password: pr0dn0tes
TGDBSERVER3DataSource:
  url: jdbc:oracle:thin:@dc1prd-scan:1521/prd3
  username: polnote_service
  password: pr0dn0tes
propertiesDomainInjector:
  env: PROD
cxf:
  path: /v2